.TH MARKDOWNMAKE 1
.SH NAME
markdownmake \- Add boilerplate to your markdown output

.SH SYNOPSIS
.B markdownmake

.SH DESCRIPTION
Finds .md files and then creates a corresponding html file, complete with starting and ending boilerplate to initialize a complete HTML document. This means the header is included, instead of just the output of the markdown command.

.SH SEE ALSO
markdown(1)

.SH AUTHOR
Jim Read (jimmydean886@hotmail.com)
