.TH SCREENLOCK.SH 5
.SH NAME
screenlock.sh \- lock the screen with a fancy background

.SH SETUP
.PP
If you haven't already, please see screenlock.sh(1). It will describe the purpose and procedures in screenlock.sh. This file is for modifying the script for actual use.

In order to use screenlock.sh, please open the file in a text editor and set an image to center in the screen, one for single screens, one for dual screens.

These can be found at lines 4 and 5 for single and dual screen configurations, respectively.

.SH SEE ALSO
convert(1), xrandr(1), i3lock(1), scrot(1), screenlock.sh(1)
