.TH UNZIPALL.SH 1
.SH NAME
unzipall \- Unzip all zip files in a directory

.SH SYNOPSIS
unzipall

.SH DESCRIPTION
Unzips everything in a directory.

This is built largely for cases where a large amount of zips are obtained from a site like bandcamp, or Linux from Scratch, and for conveinence all .zip files need be unzipped.

The script does end up creating folders for EVERY archive, regardless of whether they have a root folder.

.SH SEE ALSO
zip(1), unzip(1)

.SH AUTHOR
Jim Read (jimmydean886@hotmail.com)